### ISSUE TITLE
register seems successful, whois reports the ID as registerd but lookup on that id fails with an exceptio

### ISSUE THREAD

**Issue by fpischedda** [stx-labs/stacks.js#102]
Hi,

it seems that I've managed to register an ID after a couple of trial and errors, the preorder status of the id disappared from the info command but names command returns an empty list; whois command reports the ID as registered but the lookup fails with this exception:

$ blockstack lookup MYID.id
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/blockstack_profiles/token_verifying.py", line 114, in get_profile_from_tokens
    decoded_token = verify_token_record(token_record, public_key_or_address)
  File "/usr/local/lib/python2.7/site-packages/blockstack_profiles/token_verifying.py", line 88, in verify_token_record
    token, public_key_or_address, signing_algorithm=signing_algorithm)
  File "/usr/local/lib/python2.7/site-packages/blockstack_profiles/token_verifying.py", line 65, in verify_token
    raise ValueError("Token public key doesn't match the verifying value")
ValueError: Token public key doesn't match the verifying value
{
    "data_record": {},
    "zone_file": "$ORIGIN MYID.id\n$TTL 3600\n_http._tcp URI 10 1 \"https://blockstack.s3.amazonaws.com/MYID.id\"\n"
}

this is the output of the info command:

$ blockstack info
{
    "advanced_mode": "false",
    "cli_version": "0.0.12.7",
    "consensus_hash": "9a214fe4a0ba8b357128f34a3b608aab",
    "last_block_processed": 417463,
    "last_block_seen": 417471,
    "server_alive": true,
    "server_host": "server.blockstack.org",
    "server_port": "6264",
    "server_version": "0.0.10.3"
}

I've already restarted the registrar daemons but nothing has changed

**Comment by fpischedda** [comment]
blockstack lookup seems to work now reporting onename proofs
