### ISSUE TITLE
blockstack fails to run: `ImportError: No module named 'client'`

### ISSUE THREAD

**Issue by ntwb** [stx-labs/stacks.js#104]
``` shell
$ blockstack
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python3.5/site-packages/blockstack_client/__init__.py", line 24, in <module>
    import client
ImportError: No module named 'client'
```

The install log:

``` shell
sudo pip install blockstack --upgrade
The directory '/Users/netweb/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/netweb/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting blockstack
Requirement already up-to-date: blockstore==0.0.10.10 in /usr/local/lib/python3.5/site-packages (from blockstack)
Requirement already up-to-date: base58==0.2.2 in /usr/local/lib/python3.5/site-packages (from blockstack)
Requirement already up-to-date: cachetools==1.1.6 in /usr/local/lib/python3.5/site-packages (from blockstack)
Requirement already up-to-date: registrar==0.0.3.10 in /usr/local/lib/python3.5/site-packages (from blockstack)
Requirement already up-to-date: blockstack-client==0.0.12.7 in /usr/local/lib/python3.5/site-packages (from blockstack)
Requirement already up-to-date: virtualchain==0.0.6 in /usr/local/lib/python3.5/site-packages (from blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: kademlia==0.5 in /usr/local/lib/python3.5/site-packages (from blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: keychain==0.1.4 in /usr/local/lib/python3.5/site-packages (from blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: blockstore-client==0.0.12.10 in /usr/local/lib/python3.5/site-packages (from blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: pymongo==2.7.2 in /usr/local/lib/python3.5/site-packages (from registrar==0.0.3.10->blockstack)
Requirement already up-to-date: pycrypto==2.6.1 in /usr/local/lib/python3.5/site-packages (from registrar==0.0.3.10->blockstack)
Requirement already up-to-date: scrypt==0.7.1 in /usr/local/lib/python3.5/site-packages (from registrar==0.0.3.10->blockstack)
Requirement already up-to-date: blockcypher==1.0.63 in /usr/local/lib/python3.5/site-packages (from registrar==0.0.3.10->blockstack)
Requirement already up-to-date: tinydb==3.1.3 in /usr/local/lib/python3.5/site-packages (from registrar==0.0.3.10->blockstack)
Requirement already up-to-date: boto==2.38.0 in /usr/local/lib/python3.5/site-packages (from blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: basicrpc==0.0.2 in /usr/local/lib/python3.5/site-packages (from blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: protocoin==0.1 in /usr/local/lib/python3.5/site-packages (from blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: blockstack-profiles==0.4.3 in /usr/local/lib/python3.5/site-packages (from blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: txJSON-RPC>=0.3.1 in /usr/local/lib/python3.5/site-packages (from virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: Twisted>=15.3.0 in /usr/local/lib/python3.5/site-packages (from virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: pybitcoin>=0.9.7 in /usr/local/lib/python3.5/site-packages (from virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: rpcudp>=1.0 in /usr/local/lib/python3.5/site-packages (from kademlia==0.5->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: bitmerchant>=0.1.8 in /usr/local/lib/python3.5/site-packages (from keychain==0.1.4->blockstore==0.0.10.10->blockstack)
Collecting bitcoin>=1.1.39 (from keychain==0.1.4->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: python-dateutil==2.2 in /usr/local/lib/python3.5/site-packages (from blockcypher==1.0.63->registrar==0.0.3.10->blockstack)
Requirement already up-to-date: requests==2.4.3 in /usr/local/lib/python3.5/site-packages (from blockcypher==1.0.63->registrar==0.0.3.10->blockstack)
Requirement already up-to-date: cryptography>=1.2.3 in /usr/local/lib/python3.5/site-packages (from blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: jsontokens>=0.0.2 in /usr/local/lib/python3.5/site-packages (from blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: zone-file>=0.1.5 in /usr/local/lib/python3.5/site-packages (from blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: keylib>=0.0.2 in /usr/local/lib/python3.5/site-packages (from blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: six in /usr/local/lib/python3.5/site-packages (from txJSON-RPC>=0.3.1->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: zope.interface>=4.0.2 in /usr/local/lib/python3.5/site-packages (from Twisted>=15.3.0->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: ecdsa>=0.13 in /usr/local/lib/python3.5/site-packages (from pybitcoin>=0.9.7->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: pybitcointools==1.1.15 in /usr/local/lib/python3.5/site-packages (from pybitcoin>=0.9.7->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: commontools==0.1.0 in /usr/local/lib/python3.5/site-packages (from pybitcoin>=0.9.7->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: python-bitcoinrpc==0.1 in /usr/local/lib/python3.5/site-packages (from pybitcoin>=0.9.7->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: utilitybelt>=0.2.1 in /usr/local/lib/python3.5/site-packages (from pybitcoin>=0.9.7->virtualchain==0.0.6->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: future>=0.6 in /usr/local/lib/python3.5/site-packages (from rpcudp>=1.0->kademlia==0.5->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: u-msgpack-python>=1.5 in /usr/local/lib/python3.5/site-packages (from rpcudp>=1.0->kademlia==0.5->blockstore==0.0.10.10->blockstack)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.2.3->blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.2.3->blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: pyasn1>=0.1.8 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.2.3->blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.2.3->blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.5/site-packages (from cffi>=1.4.1->cryptography>=1.2.3->blockstack-profiles==0.4.3->blockstack-client==0.0.12.7->blockstack)
Installing collected packages: blockstack, bitcoin
  Found existing installation: bitcoin 1.1.39
    Uninstalling bitcoin-1.1.39:
      Successfully uninstalled bitcoin-1.1.39
Successfully installed bitcoin-1.1.42 blockstack-0.0.10.9

```

Env:

```
$ python -V
Python 2.7.10
$ pip -V
pip 8.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)
```

OS X 10.11.5

**Comment by odinho** [comment]
You're using Python 3.  I was thinking this bug could be the "Make it run on Python 3" bug, but I think it is better as it is.  Should at least make a better error message at first.

You can see that your pip version is Python 3.5, maybe you have `pip2` you can use?  You should probably remove the other blockstack first then, so you can be sure you're running it from Python 2 directories.

**Comment by ntwb** [comment]
Right, not sure why I had Python 3 installed, whatever it was it was important at the time, now it's not 😝 

`brew uninstall python3` and `brew install python` has me sorted with blockchain now installed.

Thanks @Velmont
