### ISSUE TITLE
Issues with commands in the release candidate branch

### ISSUE THREAD

**Issue by shea256** [stx-labs/stacks.js#107]
Hey @jcnelson @muneeb-ali I'm just documenting this here for future reference, in case anyone else runs into a similar problem.

I'm working on the release candidate branch and I'm facing a couple of issues. It might just be a problem with my particular installation but I figured I'd document it here anyway and we can always close it out.

Here's the issue I'm getting when I do `blockstack price`:

```
Traceback (most recent call last):
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/EGG-INFO/scripts/blockstack", line 54, in <module>
    result = run_cli()
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/cli.py", line 285, in run_cli
    result = method( args, config_path=config_path )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/actions.py", line 341, in cli_price
    fees = get_total_registration_fees( fqu, payment_privkey, owner_address, proxy=proxy, config_path=config_path )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/actions.py", line 229, in get_total_registration_fees
    preorder_tx_fee = estimate_preorder_tx_fee( name, data['satoshis'], payment_address, utxo_client, config_path=config_path )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/backend/nameops.py", line 61, in estimate_preorder_tx_fee
    unsigned_tx = preorder_tx( name, payment_addr, fake_owner_address, name_cost, fake_consensus_hash, utxo_client )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/tx.py", line 35, in preorder_tx
    inputs, outputs = tx_preorder( *args, **kw )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/operations/preorder.py", line 131, in make_transaction
    outputs = make_outputs(nulldata, inputs, payment_addr, fee, tx_fee)
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/operations/preorder.py", line 99, in make_outputs
    "value": calculate_change_amount(inputs, bill, dust_fee)},
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/pybitcoin-0.9.8-py2.7.egg/pybitcoin/transactions/outputs.py", line 20, in calculate_change_amount
    raise Exception('Not enough inputs for transaction.')
Exception: Not enough inputs for transaction.
```

Here's the issue I'm getting when I do `blockstack register`:

```
[2016-07-08 18:53:58,158] [DEBUG] [session:127] (98408) [98408] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-07-08 18:53:59,949] [DEBUG] [session:127] (98408) [98408] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-07-08 18:54:05,237] [ERROR] [blockstack:67] (98408) local variable 'tx_hex' referenced before assignment
Traceback (most recent call last):
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/EGG-INFO/scripts/blockstack", line 54, in <module>
    result = run_cli()
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/cli.py", line 292, in run_cli
    result = method(args, config_path=config_path)
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/actions.py", line 735, in cli_register
    fees = get_total_registration_fees(fqu, payment_privkey, owner_address, proxy=proxy, config_path=config_path)
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/actions.py", line 237, in get_total_registration_fees
    update_tx_fee = estimate_update_tx_fee( name, payment_privkey, owner_address, utxo_client, config_path=config_path )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/backend/nameops.py", line 130, in estimate_update_tx_fee
    signed_subsidized_tx = sign_tx( subsidized_tx, fake_privkey )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/blockstack_client-0.0.13.0-py2.7.egg/blockstack_client/tx.py", line 115, in sign_tx
    return sign_all_unsigned_inputs( private_key_hex, tx_hex )
  File "/Users/ryanshea/.virtualenvs/cli4/lib/python2.7/site-packages/pybitcoin-0.9.8-py2.7.egg/pybitcoin/transactions/network.py", line 205, in sign_all_unsigned_inputs
    return tx_hex
UnboundLocalError: local variable 'tx_hex' referenced before assignment
```

The other commands are working perfect for me. Please let me know if you know what's going on. In the meantime, I'm going to be looking through the files in the traceback to see if I can pinpoint what's causing the issues.

**Comment by jcnelson** [comment]
The latter bug is in pybitcoin 0.9.8 and previous (but fixed in 0.9.9 and in the `develop` branch, which I just pushed to PyPI).

The former is due to the CLI not handling the case when there aren't enough inputs to do a fee estimation (or generate a transaction, for that matter).  My latest push should fix that; please let me know if it doesn't.  Will be testing and updating as needed.

**Comment by shea256** [comment]
OK great, awesome, thank you!

**Comment by jcnelson** [comment]
Should be fixed now

**Comment by shea256** [comment]
Awesome!
