### ISSUE TITLE
Confusing error message on known-valid address in `makeStandardFungiblePostCondition`

### ISSUE THREAD

**Issue by mcintyre94** [stx-labs/stacks.js#1238]
**Describe the bug**

When I call `makeStandardFungiblePostCondition` the first param is `address: string`. This is documented as "@param address - the c32check address": https://github.com/hirosystems/stacks.js/blob/master/packages/transactions/src/builders.ts#L1159. 

When I call it with a known-valid address in the first param, I get an error message `Error: Invalid c32 address: must start with "S"`

**What version of Stacks.js are you using?**
`@stacks/transactions` v4.0.0

**Is the bug present in the Stacks.js CLI, Gaia hub, Connect or Blockstack Browser?**
NPM library `@stacks/transactions`

**To Reproduce**

- Replit: https://replit.com/@mcintyre94/ft-post-condition?v=1
- This includes a call to `makeStandardSTXPostCondition` which succeeds, and then a call to `makeStandardFungiblePostCondition` using the exact same address which errors

**Expected behavior**

- There should be no error message caused by the address in the call to `makeStandardFungiblePostCondition`

**Screenshots**

Error message in my own app:

<img width="948" alt="Screenshot 2022-04-20 at 17 40 16" src="https://user-images.githubusercontent.com/1711350/164286253-20648896-c33b-4f58-ab8c-7abe15bf2160.png">

**Console log**

From the replit:

```
{
  cond1: {
    type: 5,
    conditionType: 0,
    principal: { type: 1, prefix: 2, address: [Object] },
    conditionCode: 1,
    amount: 1n
  }
}
Error: Invalid c32 address: must start with "S"
    at c32addressDecode (/home/runner/ft-post-condition/node_modules/c32check/lib/address.js:54:15)
    at createAddress (/home/runner/ft-post-condition/node_modules/@stacks/transactions/dist/postcondition-types.js:37:57)
    at createAssetInfo (/home/runner/ft-post-condition/node_modules/@stacks/transactions/dist/postcondition-types.js:30:18)
    at parseAssetInfoString (/home/runner/ft-post-condition/node_modules/@stacks/transactions/dist/postcondition-types.js:9:23)
    at createFungiblePostCondition (/home/runner/ft-post-condition/node_modules/@stacks/transactions/dist/postcondition.js:25:68)
    at makeStandardFungiblePostCondition (/home/runner/ft-post-condition/node_modules/@stacks/transactions/dist/builders.js:430:60)
    at Object.<anonymous> (/home/runner/ft-post-condition/index.js:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Vivaldi
- Version: 5.2.2623.39 (Stable channel) (arm64) 

**Smartphone (please complete the following information):**

- N/A

**Additional context**

The documentation of `address` is identical to the same address parameter for `makeStandardSTXPostCondition`: https://github.com/hirosystems/stacks.js/blob/master/packages/transactions/src/builders.ts#L1117

So I'd expect that any address I can pass to `makeStandardSTXPostCondition` would also work in `makeStandardFungiblePostCondition`

**Comment by mcintyre94** [comment]
Closing. The issue was that the 4th param is expected to be a contract address. The error line in my app just somehow ended up being wrong and flagged the correct 1st param. Sanity restored! :)
