### ISSUE TITLE
blockstore-cli launch

### ISSUE THREAD

**Issue by RCasatta** [stx-labs/stacks.js#13]
```
git clone https://github.com/blockstack/blockstore-client
cd blockstore-client
python setup.py build
sudo python setup.py install
blockstore-cli
Traceback (most recent call last):
  File "/usr/local/bin/blockstore-cli", line 5, in <module>
    pkg_resources.run_script('blockstore-client==0.0.3', 'blockstore-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 547, in <module>
    run_cli()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 77, in run_cli
    storage_drivers = conf['storage_drivers']
KeyError: 'storage_drivers'
```

on Ubuntu 12.04 and Max OS X yosemite

**Comment by muneeb-ali** [comment]
Try the following .ini file

```
[blockstore-client]
server=127.0.0.1
port=6264
storage=disk
```

at ~/.blockstore-client/blockstore-client.ini

Also, we plan to release the stable / easy to install version next week and are working through these installation issues as we speak :-)

**Comment by RCasatta** [comment]
it starts now, however i thought it worked without blockstored... which i had some problem during install...
Waiting more stable versions next week.
