### ISSUE TITLE
Upgrade from v4 to v5: Error: Invalid byte sequence

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1377]
**Describe the bug**

When upgrading the Stacks.js deps from v4 to v5 I am receiving one of the following error `Error: hexToBytes: received invalid unpadded hex119` or `Error: Invalid byte sequence`. Does this has to do with the signature prefix change? It's not clear from the codebase if one has to do any change to get it to work.

Log:

```
Error: hexToBytes: received invalid unpadded hex119
    at hexToBytes (/Users/leo/dev/sigle/sigle/node_modules/.pnpm/@noble+secp256k1@1.6.3/node_modules/@noble/secp256k1/lib/index.js:528:15)
    at ensureBytes (/Users/leo/dev/sigle/sigle/node_modules/.pnpm/@noble+secp256k1@1.6.3/node_modules/@noble/secp256k1/lib/index.js:544:63)
    at Function.fromSignature (/Users/leo/dev/sigle/sigle/node_modules/.pnpm/@noble+secp256k1@1.6.3/node_modules/@noble/secp256k1/lib/index.js:304:19)
    at publicKeyFromSignatureVrs (/Users/leo/dev/sigle/sigle/node_modules/.pnpm/@stacks+transactions@5.0.1/node_modules/@stacks/transactions/dist/keys.js:40:37)
    at publicKeyFromSignatureRsv (/Users/leo/dev/sigle/sigle/node_modules/.pnpm/@stacks+transactions@5.0.1/node_modules/@stacks/transactions/dist/keys.js:46:12)
    at eval (webpack-internal:///(api)/./src/modules/auth/sign-in-with-stacks/signInWithStacksMessage.ts:196:114)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///(api)/./src/modules/auth/sign-in-with-stacks/signInWithStacksMessage.ts:195:87)
    at new Promise (<anonymous>)
    at SignInWithStacksMessage.verify (webpack-internal:///(api)/./src/modules/auth/sign-in-with-stacks/signInWithStacksMessage.ts:130:16)
```

**To Reproduce**

1. Go to https://github.com/sigle/sigle/pull/720 and clone the branch locally
2. `pnpm install && cd sigle`
3. `pnpm dev`
4. Login and try to sign the message and see error

**Expected behavior**

Upgrade should work just fine.

**Comment by janniks** [comment]
Will check now 🤔

**Comment by pradel** [comment]
Thanks @janniks !

**Comment by janniks** [comment]
This is part of the change from Buffers to UInt8Arrays. There is some more information in the [migration guide](https://github.com/hirosystems/stacks.js/blob/master/.github/MIGRATION.md#buffer-to-uint8array). In this case it's tricky to find, since `Buffer` wasn't mentioned in the previous code, even though it was a buffer type. The `.toString('hex')` is something that mostly works on Buffers, and in this case JS ignore the `'hex'` part and just converted the bytes to an array-string, which isn't hex compatible.

[This patch](https://github.com/sigle/sigle/pull/721) should solve the issue.

**Comment by pradel** [comment]
Thanks for the help @janniks !
