### ISSUE TITLE
blockstack-cli upgrade issue

### ISSUE THREAD

**Issue by dgdosen** [stx-labs/stacks.js#146]
```
> blockstack info

Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/__init__.py", line 25, in <module>
    import client
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/client.py", line 59, in <module>
    from wallet import *
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/wallet.py", line 62, in <module>
    from .backend.crypto.utils import get_address_from_privkey, get_pubkey_from_privkey
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/__init__.py", line 1, in <module>
    from registrar import *
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/registrar.py", line 45, in <module>
    from .queue import get_queue_state, in_queue, queue_removeall
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/queue.py", line 11, in <module>
    import sqlite3
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

I've got this issue when upgrading blockstack on macos

I don't want to destroy any wallet/registration info I have - any ideas why this happened?

Thanks!

**Comment by pandu-rao** [comment]
It appears that your Mac OS installation of python is unable to find the _sqlite3.so C extension module.

See if it exists on the filesystem.
`find /usr/local -name _sqlite3.so`

If it doesn't exist, try:
`brew install sqlite --with-functions`

**Comment by dgdosen** [comment]
I had upgraded homebrew python on my mac as well - that had a couple of issues.  Fixed that, and now it's working.  

I was mainly worried about the wallet I had in blockstack.

Case closed...

**Comment by oso4** [comment]
Having trouble connecting to the core:

$ blockstack info
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/app.py", line 37, in <module>
    import jsontokens
  File "/usr/local/lib/python2.7/site-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/usr/local/lib/python2.7/site-packages/jsontokens/token_signer.py", line 24, in <module>
    from .key_loading import load_signing_key
  File "/usr/local/lib/python2.7/site-packages/jsontokens/key_loading.py", line 14, in <module>
    from cryptography.hazmat.backends.multibackend import MultiBackend
ImportError: No module named multibackend

**Comment by shea256** [comment]
Hey @oso4 thanks for reporting and happy to help you out. Can you please open an issue in https://github.com/blockstack/blockstack-core?
