### ISSUE TITLE
get_name_zonefile fails

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#151]
When called in non-interactive mode, `get_name_zonefile` fails with the following output:

``````
(venv) larry@blockstack-explorer-1:/home/dev/explorer-api$ blockstack get_name_zonefile larry.id
[2016-10-27 09:55:57,009] [DEBUG] [spv:103] (7936.140400560101184) Using mainnet
[2016-10-27 09:55:57,254] [DEBUG] [cli:210] (7936.140400560101184) Enabling advanced methods
[2016-10-27 09:55:57,301] [DEBUG] [client:134] (7936.140400560101184) Loaded storage driver 'disk'
[2016-10-27 09:55:57,302] [DEBUG] [client:134] (7936.140400560101184) Loaded storage driver 'blockstack_resolver'
[2016-10-27 09:55:57,302] [DEBUG] [client:134] (7936.140400560101184) Loaded storage driver 'blockstack_server'
[2016-10-27 09:55:57,303] [DEBUG] [client:134] (7936.140400560101184) Loaded storage driver 'http'
[2016-10-27 09:55:57,303] [DEBUG] [client:134] (7936.140400560101184) Loaded storage driver 'dht'
[2016-10-27 09:55:57,303] [ERROR] [blockstack:80] (7936.140400560101184) 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/dev/explorer-api/venv/bin/blockstack", line 67, in <module>
    result = run_cli()
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/cli.py", line 287, in run_cli
    result = method( args, config_path=config_path )
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 2330, in cli_advanced_get_name_zonefile
    if parse_json.lower() in ['true', '1']:
AttributeError: 'NoneType' object has no attribute 'lower'
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/home/dev/explorer-api/venv/bin/blockstack\", line 67, in <module>\n    result = run_cli()\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/cli.py\", line 287, in run_cli\n    result = method( args, config_path=config_path )\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/actions.py\", line 2330, in cli_advanced_get_name_zonefile\n    if parse_json.lower() in ['true', '1']:\nAttributeError: 'NoneType' object has no attribute 'lower'\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
(venv) larry@blockstack-explorer-1:/home/dev/explorer-api$```

``````

**Comment by jcnelson** [comment]
This should be fixed now.  Thanks for reporting!

**Comment by larrysalibra** [comment]
Works for me. Thank you.
