### ISSUE TITLE
Valid name assertion fails for valid name

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#153]
`get_names_in_namespace` and `get_all_names` result in failed valid name assertion for the name: `12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id`

Running `blockstack get_names_in_namespace id` results in a failed assertion and the following output:

```
(venv) larry@blockstack-explorer-1:~$ blockstack get_names_in_namespace id
[2016-10-27 10:43:12,543] [DEBUG] [spv:103] (8547.140237091108672) Using mainnet
[2016-10-27 10:43:12,784] [DEBUG] [cli:210] (8547.140237091108672) Enabling advanced methods
[2016-10-27 10:43:12,835] [DEBUG] [client:134] (8547.140237091108672) Loaded storage driver 'disk'
[2016-10-27 10:43:12,835] [DEBUG] [client:134] (8547.140237091108672) Loaded storage driver 'blockstack_resolver'
[2016-10-27 10:43:12,836] [DEBUG] [client:134] (8547.140237091108672) Loaded storage driver 'blockstack_server'
[2016-10-27 10:43:12,836] [DEBUG] [client:134] (8547.140237091108672) Loaded storage driver 'http'
[2016-10-27 10:43:12,836] [DEBUG] [client:134] (8547.140237091108672) Loaded storage driver 'dht'
[2016-10-27 10:43:13,248] [ERROR] [proxy:921] (8547.140237091108672) Invalid name 12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id
Traceback (most recent call last):
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/proxy.py", line 918, in get_names_in_namespace_page
    assert scripts.is_name_valid(str(n)), ("Invalid name %s" % str(n))
AssertionError: Invalid name 12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id
AssertionError: Invalid name 12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id
(venv) larry@blockstack-explorer-1:~$
```

Running `blockstack get_all_names` results in a failed assertion and the following output:

```
(venv) larry@blockstack-explorer-1:~$ blockstack get_all_names
[2016-10-27 11:02:56,208] [DEBUG] [spv:103] (8667.140473668667200) Using mainnet
[2016-10-27 11:02:56,437] [DEBUG] [cli:210] (8667.140473668667200) Enabling advanced methods
[2016-10-27 11:02:56,485] [DEBUG] [client:134] (8667.140473668667200) Loaded storage driver 'disk'
[2016-10-27 11:02:56,485] [DEBUG] [client:134] (8667.140473668667200) Loaded storage driver 'blockstack_resolver'
[2016-10-27 11:02:56,485] [DEBUG] [client:134] (8667.140473668667200) Loaded storage driver 'blockstack_server'
[2016-10-27 11:02:56,486] [DEBUG] [client:134] (8667.140473668667200) Loaded storage driver 'http'
[2016-10-27 11:02:56,486] [DEBUG] [client:134] (8667.140473668667200) Loaded storage driver 'dht'
[2016-10-27 11:03:02,677] [ERROR] [blockstack:80] (8667.140473668667200) Invalid name '12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id'
Traceback (most recent call last):
  File "/home/dev/explorer-api/venv/bin/blockstack", line 67, in <module>
    result = run_cli()
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/cli.py", line 287, in run_cli
    result = method( args, config_path=config_path )
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 2394, in cli_advanced_get_all_names
    result = get_all_names(offset=offset, count=count)
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/proxy.py", line 867, in get_all_names
    page = get_all_names_page( offset + len(all_names), page_size, proxy=proxy )
  File "/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/proxy.py", line 796, in get_all_names_page
    assert scripts.is_name_valid(str(n)), ("Invalid name '%s'" % str(n))
AssertionError: Invalid name '12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id'
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/home/dev/explorer-api/venv/bin/blockstack\", line 67, in <module>\n    result = run_cli()\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/cli.py\", line 287, in run_cli\n    result = method( args, config_path=config_path )\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/actions.py\", line 2394, in cli_advanced_get_all_names\n    result = get_all_names(offset=offset, count=count)\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/proxy.py\", line 867, in get_all_names\n    page = get_all_names_page( offset + len(all_names), page_size, proxy=proxy )\n  File \"/home/dev/explorer-api/venv/local/lib/python2.7/site-packages/blockstack_client/proxy.py\", line 796, in get_all_names_page\n    assert scripts.is_name_valid(str(n)), (\"Invalid name '%s'\" % str(n))\nAssertionError: Invalid name '12ntgsk68wxgg7gzsmsmdjgkgnynqngwsc.id'\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
(venv) larry@blockstack-explorer-1:~$ 
```

**Comment by larrysalibra** [comment]
fixed in https://github.com/blockstack/blockstack-cli/commit/ee25a99aac022d58452901f671fd92798f1f892d thanks @jcnelson
