### ISSUE TITLE
get_nameops_at 436297 fails with KeyError

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#155]
Running `blockstack get_nameops_at 436297` fails with KeyError as in example below:

```
(venv) larry@blockstack-explorer-1:~/blockstack-integration-tests$ blockstack get_nameops_at 436297
[2016-10-28 10:50:07,249] [DEBUG] [spv:103] (18090.140633212950336) Using mainnet
[2016-10-28 10:50:07,471] [DEBUG] [cli:210] (18090.140633212950336) Enabling advanced methods
[2016-10-28 10:50:07,516] [DEBUG] [client:134] (18090.140633212950336) Loaded storage driver 'disk'
[2016-10-28 10:50:07,516] [DEBUG] [client:134] (18090.140633212950336) Loaded storage driver 'blockstack_resolver'
[2016-10-28 10:50:07,517] [DEBUG] [client:134] (18090.140633212950336) Loaded storage driver 'blockstack_server'
[2016-10-28 10:50:07,517] [DEBUG] [client:134] (18090.140633212950336) Loaded storage driver 'http'
[2016-10-28 10:50:07,517] [DEBUG] [client:134] (18090.140633212950336) Loaded storage driver 'dht'
[2016-10-28 10:50:08,847] [DEBUG] [proxy:1513] (18090.140633212950336) 4 nameops at 436297
[2016-10-28 10:50:08,848] [ERROR] [blockstack:80] (18090.140633212950336) 'name'
Traceback (most recent call last):
  File "/home/larry/blockstack-integration-tests/venv/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/EGG-INFO/scripts/blockstack", line 67, in <module>
    result = run_cli()
  File "/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/cli.py", line 287, in run_cli
    result = method( args, config_path=config_path )
  File "/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/actions.py", line 2401, in cli_advanced_get_nameops_at
    result = get_nameops_at(int(args.block_id))
  File "/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/proxy.py", line 1520, in get_nameops_at
    history_rows = nameop_histories.get(nameop['name'])
KeyError: 'name'
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/home/larry/blockstack-integration-tests/venv/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/EGG-INFO/scripts/blockstack\", line 67, in <module>\n    result = run_cli()\n  File \"/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/cli.py\", line 287, in run_cli\n    result = method( args, config_path=config_path )\n  File \"/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/actions.py\", line 2401, in cli_advanced_get_nameops_at\n    result = get_nameops_at(int(args.block_id))\n  File \"/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/proxy.py\", line 1520, in get_nameops_at\n    history_rows = nameop_histories.get(nameop['name'])\nKeyError: 'name'\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
(venv) larry@blockstack-explorer-1:~/blockstack-integration-tests$ 
```

**Comment by jcnelson** [comment]
Should be fixed now.  Thanks for reporting!
