### ISSUE TITLE
get_nameops_at 436386 core dump

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#156]
Running `blockstack get_nameops_at 436386` results in a core dump:

cli at commit: https://github.com/blockstack/blockstack-cli/commit/d7fcb918ebc1cd4b36ff8434711a9634d133e0a2

core at commit: https://github.com/blockstack/blockstack-core/commit/1cee73473c5fbd7867a425cde2358eb1b7336cb1

Note that I updated to these versions with the new hard fork deadline after the previous deadline passed. Could that be the cause?

```
(venv) larry@blockstack-explorer-1:/home/dev/blockstack-bitcore$ blockstack get_nameops_at 436386
[2016-10-29 01:34:25,245] [DEBUG] [spv:103] (22364.140056735565632) Using mainnet
[2016-10-29 01:34:25,458] [DEBUG] [cli:210] (22364.140056735565632) Enabling advanced methods
[2016-10-29 01:34:25,503] [DEBUG] [client:134] (22364.140056735565632) Loaded storage driver 'disk'
[2016-10-29 01:34:25,503] [DEBUG] [client:134] (22364.140056735565632) Loaded storage driver 'blockstack_resolver'
[2016-10-29 01:34:25,504] [DEBUG] [client:134] (22364.140056735565632) Loaded storage driver 'blockstack_server'
[2016-10-29 01:34:25,504] [DEBUG] [client:134] (22364.140056735565632) Loaded storage driver 'http'
[2016-10-29 01:34:25,504] [DEBUG] [client:134] (22364.140056735565632) Loaded storage driver 'dht'
[2016-10-29 01:34:28,170] [DEBUG] [proxy:1577] (22364.140056735565632) 4 nameops at 436386
[2016-10-29 01:34:28,621] [DEBUG] [proxy:1602] (22364.140056735565632) elbertwijaya.id had 1 operations (1 history rows, 1 historic nameops, txids: [u'3476f2358ec58640f1a46f7e123528c6bd09576d492dfab957f56d943a595ce7']) at 436386
[2016-10-29 01:34:28,621] [DEBUG] [__init__:298] (22364.140056735565632) apply SNV QURIKS on elbertwijaya.id at 436386 (created with NAME_PREORDER)
[2016-10-29 01:34:29,093] [DEBUG] [proxy:1602] (22364.140056735565632) sophbug.id had 1 operations (2 history rows, 1 historic nameops, txids: [u'd3f6173c63c656645a5d0bcd89fed1f5385f86c2b27baf6067abc5bfd680ab28']) at 436386
[2016-10-29 01:34:29,093] [DEBUG] [__init__:298] (22364.140056735565632) apply SNV QURIKS on sophbug.id at 436386 (created with NAME_PREORDER)
[2016-10-29 01:34:29,523] [DEBUG] [proxy:1602] (22364.140056735565632) autohome.id had 1 operations (2 history rows, 1 historic nameops, txids: [u'f0f5a7024030200fbb95048229bcf32ceff49c561b91960302feab77a35a650e']) at 436386
[2016-10-29 01:34:29,523] [DEBUG] [__init__:298] (22364.140056735565632) apply SNV QURIKS on autohome.id at 436386 (created with NAME_PREORDER)
[2016-10-29 01:34:29,524] [ERROR] [__init__:193] (22364.140056735565632) 'NAME_PREORDER'
Traceback (most recent call last):
  File "/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/operations/__init__.py", line 190, in nameop_restore_from_history
    assert nameop_is_history_snapshot( historical_rec ), "No history for incomplete name"
  File "/home/larry/blockstack-integration-tests/venv/local/lib/python2.7/site-packages/blockstack_client-0.14.0-py2.7.egg/blockstack_client/operations/__init__.py", line 116, in nameop_is_history_snapshot
    consensus_fields = OPFIELDS[opcode]
KeyError: 'NAME_PREORDER'
[2016-10-29 01:34:29,524] [DEBUG] [__init__:194] (22364.140056735565632) 
{
    "address": "1KXL6Tfw852ZDDVfjuvB5S6BMScm7W27LZ", 
    "block_number": 436386, 
    "consensus_hash": "829c2ee25bfd74f1ba0148a3a2dc4a30", 
    "op": "?", 
    "op_fee": 25000, 
    "opcode": "NAME_PREORDER", 
    "preorder_hash": "f6594c7e14214827682d090546a3509a1c4c8b5d", 
    "sender": "76a914cb2eae93d3dc8741fd2cd8e804250ddd83d6b49888ac", 
    "sender_pubkey": "021d347584e4a3cf77be18efc6c7185ebdc02d15d9496534d468e78943790bc789", 
    "txid": "23dd31bae87fb1c110b895f7bcb914f3cd6a93d1b06d182fb2dff28cc133eada", 
    "vtxindex": 79
}
[2016-10-29 01:34:29,524] [ERROR] [__init__:195] (22364.140056735565632) FATAL: tried to restore history for incomplete record
Aborted (core dumped)
(venv) larry@blockstack-explorer-1:/home/dev/blockstack-bitcore$

``
```

**Comment by larrysalibra** [comment]
I restored my database to pre-original fork block height `435455` and allowed core to re-index up to the current block height and the problem went away.

**Comment by larrysalibra** [comment]
I'm not sure a core dump is the best way to handle this situation. Reopening this issue for @jcnelson 's input.

**Comment by jcnelson** [comment]
Thanks for reporting!  Sorry for the later turn-around time.

The bug is that `opcode` here is an inappropriate key for the `OPFIELDS` dict.  Will push a fix for this.

Regarding core dumps, this is an artifact of the fact that the client called `abort()`, which on your system may trigger a core dump.  The reason we went with `abort()` over `exit()` is because `exit()` doesn't necessarily kill all threads or stop the program.  A better solution that won't dump core might be `kill( os.getpid(), signal.SIGKILL )`.

**Comment by jcnelson** [comment]
This should be working now.  Please re-open in blockstack-core if not.
