### ISSUE TITLE
price command hangs

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#158]
Running `blockstack price larry.id` doesn't return the price (nothing seems to happen) on the block explorer server. After waiting for ~5 minutes and killing the running command, there was the following output:

```
(blockstack-venv) larry@blockstack-explorer-1:~$ blockstack price larry.id
^CTraceback (most recent call last):
  File "/home/dev/blockstack-venv/bin/blockstack", line 67, in <module>
    result = run_cli()
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/cli.py", line 287, in run_cli
    result = method( args, config_path=config_path )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 479, in cli_price
    fees = get_total_registration_fees( fqu, payment_privkey_info, owner_privkey_info, proxy=proxy, config_path=config_path, payment_address=payment_address )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 271, in get_total_registration_fees
    preorder_tx_fee = estimate_preorder_tx_fee( name, data['satoshis'], payment_address, utxo_client, owner_privkey_params=get_privkey_info_params(owner_privkey_info), config_path=config_path, include_dust=True )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/backend/nameops.py", line 116, in estimate_preorder_tx_fee
    fake_privkey = make_fake_privkey_info( owner_privkey_params )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/backend/nameops.py", line 103, in make_fake_privkey_info
    return virtualchain.make_multisig_wallet( m, n )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/virtualchain/lib/blockchain/bitcoin_blockchain/multisig.py", line 82, in make_multisig_wallet
    pk = BitcoinPrivateKey().to_wif()
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/pybitcoin/privatekey.py", line 55, in __init__
    secret_exponent = random_secret_exponent(self._curve.order)
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/pybitcoin/privatekey.py", line 32, in random_secret_exponent
    random_hex = hexlify(dev_random_entropy(32))
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/utilitybelt/entropy.py", line 38, in dev_random_entropy
    return open("/dev/random", "rb").read(numbytes)
KeyboardInterrupt
(blockstack-venv) larry@blockstack-explorer-1:~$
```

The computer is running `Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-79-generic x86_64)` on a digital ocean virtual machine.

I tried running the same command both using the local blockstack node and `node.blockstack.org` with similar results.

I also tried the same command on macOS both using `node.blockstack.org` and the blockstack explorer server as servers and the `price` command completed with out issue.

**Comment by jcnelson** [comment]
> The computer is running Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-79-generic x86_64) on a digital ocean virtual machine.

That's probably why.  The VM probably doesn't have enough entropy, so reads on `/dev/random` will block.  Try installing the `rng-tools` package and starting `rngd` to seed `/dev/random` with data from `/dev/urandom`.

**Comment by larrysalibra** [comment]
Installing `rng-tools` fixed it. Thanks. 

Can we detect this issue at installation or runtime? Maybe add a timeout that suggests users try to install this if there's not enough entropy? I imagine many will use this on a VM.

**Comment by jcnelson** [comment]
That's a good point.  To keep it simple, we could make `rng-tools` a `Suggests:` dependency in it's debian package, and make a note to install it by default on the README.

> Maybe add a timeout that suggests users try to install this if there's not enough entropy?

I can do this for `utilitybelt`, which is a package we control (and the source of this particular error).

**Comment by jcnelson** [comment]
Added this: https://github.com/blockstack/python-utilitybelt/pull/8

**Comment by larrysalibra** [comment]
Since installing `rng-tools` is now suggested and solves this problem, I'm going to close the issue. Please re-open if it reappears!
