### ISSUE TITLE
KeyError: 'storage_drivers'

### ISSUE THREAD

**Issue by peacekeeper** [stx-labs/stacks.js#16]
Just cloned commit 8cd21f7cddc1610a64a526341fc994266f208450 and built and installed it. When starting, getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/blockstore-cli", line 5, in <module>
    pkg_resources.run_script('blockstore-client==0.0.3', 'blockstore-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 609, in <module>
    run_cli()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 78, in run_cli
    storage_drivers = conf['storage_drivers']
KeyError: 'storage_drivers'
```

I assume this means it's not configured correctly, but 1. there should be a better error, and 2. I already have blockstored running on the same machine, so not sure how to configure blockstore-client separately?

**Comment by peacekeeper** [comment]
i discovered that if i delete ~/.blockstore-client/, then I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/blockstore-cli", line 5, in <module>
    pkg_resources.run_script('blockstore-client==0.0.3', 'blockstore-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 609, in <module>
    run_cli()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 73, in run_cli
    conf = config.get_config()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/blockstore_client/config.py", line 96, in get_config
    rc = make_default_config()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.3-py2.7.egg/blockstore_client/config.py", line 67, in make_default_config
    parser.set('blockstore-client', 'server', BLOCKSTORED_SERVER)
NameError: global name 'parser' is not defined
```

**Comment by jcnelson** [comment]
@peacekeeper The first error happens when the blockstore-cli config file does not specify a set of storage drivers to use.  I will add a configuration wizard to blockstore-cli like we have in Blockstore already.

The second error is clearly a bug.  The `parser` variable should have been initialized.

**Comment by peacekeeper** [comment]
Thx, for now I managed to manually create a working ~/.blockstore-client/blockstore-client.ini file:

```
[blockstore-client]
server = 127.0.0.1
port = 6264
metadata = /root/.blockstore-client/metadata
storage = dht
```

Maybe the wiki could have an example like this.

**Comment by rllola** [comment]
+1 
I have the same issue

**Comment by muneeb-ali** [comment]
This has been resolved in latest version. Please checkout the latest version of the client and cli!
