### ISSUE TITLE
Failed to store immutable data

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#166]
I tried out the `put_immutable` command and despite [broadcasting a transaction](https://explorer.blockstack.org/nameops/439915), it didn't seem to work.  It looks like there was a problem replicating the zonefile:

```
(blockstack-venv)Tesla:venv larry$ blockstack put_immutable 
[2016-11-21 19:23:03,623] [DEBUG] [spv:103] (31942.140735943119808) Using mainnet
[2016-11-21 19:23:04,111] [DEBUG] [cli:210] (31942.140735943119808) Enabling advanced methods
usage: blockstack put_immutable [-h] name data_id data
blockstack put_immutable: error: too few arguments
[2016-11-21 19:23:04,144] [DEBUG] [client:100] (31942.140735943119808) Connect to node.blockstack.org:6264
[2016-11-21 19:23:04,203] [DEBUG] [client:135] (31942.140735943119808) Loaded storage driver 'disk'
[2016-11-21 19:23:04,203] [DEBUG] [client:135] (31942.140735943119808) Loaded storage driver 'blockstack_resolver'
[2016-11-21 19:23:04,204] [DEBUG] [client:135] (31942.140735943119808) Loaded storage driver 'blockstack_server'
[2016-11-21 19:23:04,204] [DEBUG] [client:135] (31942.140735943119808) Loaded storage driver 'http'
[2016-11-21 19:23:04,204] [DEBUG] [client:135] (31942.140735943119808) Loaded storage driver 'dht'

Interactive prompt engaged.  Press Ctrl+C to quit
Help for 'put_immutable': Put immutable data into a zonefile

The name to receive the data ('name'): devname0.id
The name of the data ('data_id'): test
The JSON-formatted data to store ('data'): {"key": "value"}         
[2016-11-21 19:23:24,620] [DEBUG] [rpc:793] (31942.140735943119808) RPC running (/Users/larry/.blockstack/api_endpoint.pid)
[2016-11-21 19:23:24,620] [DEBUG] [rpc:843] (31942.140735943119808) RPC endpoint already running (/Users/larry/.blockstack)
[2016-11-21 19:23:24,631] [DEBUG] [rpc:452] (31942.140735943119808) Connect to RPC at localhost:6270
[2016-11-21 19:23:26,194] [DEBUG] [rpc:452] (31942.140735943119808) Connect to RPC at localhost:6270
[2016-11-21 19:23:33,435] [DEBUG] [scripts:372] (31942.140735943119808) 16hLf31sbg9SJtFpxURNxpddEqkgL4Jmi9 will subsidize 21000 (ops+dust) satoshi
[2016-11-21 19:23:33,751] [DEBUG] [blockchain:57] (31942.140735943119808) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/.blockstack/client.ini)
[2016-11-21 19:23:33,752] [DEBUG] [session:129] (31942.140735943119808) [31942] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-11-21 19:23:34,491] [DEBUG] [nameops:298] (31942.140735943119808) update tx 1374 bytes, 42548 satoshis txfee
[2016-11-21 19:23:34,493] [DEBUG] [nameops:82] (31942.140735943119808) dust_fee is 21000
[2016-11-21 19:23:34,493] [DEBUG] [nameops:303] (31942.140735943119808) Additional dust fee: 21000
[2016-11-21 19:23:38,565] [DEBUG] [profile:154] (31942.140735943119808) Fetched a88cbc639d18170d847bb80950de27000caf6696 from Atlas peer node.blockstack.org:6264
[2016-11-21 19:23:38,573] [WARNING] [profile:235] (31942.140735943119808) No data public key set; falling back to hash of data and/or owner public key for profile authentication
[2016-11-21 19:23:38,573] [DEBUG] [storage:440] (31942.140735943119808) get_mutable devname0.id
[2016-11-21 19:23:38,573] [DEBUG] [storage:480] (31942.140735943119808) Try http (https://www.larrysalibra.com/blockstack-data/devname0.id/profile.json)
[2016-11-21 19:23:38,780] [DEBUG] [storage:236] (31942.140735943119808) Verified with 1A9gp5evvELwaizkA44wUuzAcQiPHkKWWP
[2016-11-21 19:23:38,780] [DEBUG] [storage:510] (31942.140735943119808) loaded 'https://www.larrysalibra.com/blockstack-data/devname0.id/profile.json' with http
[2016-11-21 19:23:40,849] [DEBUG] [blockchain:57] (31942.140735943119808) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/.blockstack/client.ini)
[2016-11-21 19:23:40,849] [DEBUG] [session:129] (31942.140735943119808) [31942] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-11-21 19:23:52,397] [DEBUG] [scripts:372] (31942.140735943119808) 16hLf31sbg9SJtFpxURNxpddEqkgL4Jmi9 will subsidize 21000 (ops+dust) satoshi
[2016-11-21 19:23:52,694] [DEBUG] [blockchain:57] (31942.140735943119808) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/.blockstack/client.ini)
[2016-11-21 19:23:52,694] [DEBUG] [session:129] (31942.140735943119808) [31942] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-11-21 19:23:53,409] [DEBUG] [nameops:298] (31942.140735943119808) update tx 1374 bytes, 42548 satoshis txfee
[2016-11-21 19:23:53,409] [DEBUG] [nameops:765] (31942.140735943119808) Updating (devname0.id, 60ef539a835ec02c5ad87892345e4f559cf97420)
[2016-11-21 19:23:53,410] [DEBUG] [nameops:766] (31942.140735943119808) <owner, payment> (1A9gp5evvELwaizkA44wUuzAcQiPHkKWWP, 16hLf31sbg9SJtFpxURNxpddEqkgL4Jmi9) tx_fee = 42548.0
[2016-11-21 19:23:56,704] [DEBUG] [scripts:370] (31942.140735943119808) 16hLf31sbg9SJtFpxURNxpddEqkgL4Jmi9 will subsidize 21000 (ops+dust) + 42548.0 (txfee) satoshi
[2016-11-21 19:23:58,173] [DEBUG] [blockchain:57] (31942.140735943119808) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/.blockstack/client.ini)
[2016-11-21 19:23:58,174] [DEBUG] [session:129] (31942.140735943119808) [31942] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2016-11-21 19:23:58,750] [DEBUG] [storage:553] (31942.140735943119808) put_immutable_data(9724c1e20e6e3e4d7f57ed25f9d4efb006e508590d528c90da597f6a775c13e5), required=
[2016-11-21 19:23:58,750] [DEBUG] [storage:569] (31942.140735943119808) Try 'disk'
[2016-11-21 19:23:58,750] [DEBUG] [disk:181] (31942) Stored to '/Users/larry/.blockstack/storage-disk/immutable/9724c1e20e6e3e4d7f57ed25f9d4efb006e508590d528c90da597f6a775c13e5'
[2016-11-21 19:23:58,751] [DEBUG] [storage:585] (31942.140735943119808) Replication succeeded with 'disk'
[2016-11-21 19:23:58,751] [DEBUG] [storage:569] (31942.140735943119808) Try 'blockstack_resolver'
[2016-11-21 19:23:58,751] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'blockstack_resolver'
[2016-11-21 19:23:58,751] [DEBUG] [storage:569] (31942.140735943119808) Try 'blockstack_server'
[2016-11-21 19:23:58,759] [ERROR] [blockstack_server:149] (31942) Failed to parse zone file for 9724c1e20e6e3e4d7f57ed25f9d4efb006e508590d528c90da597f6a775c13e5
[2016-11-21 19:23:58,759] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'blockstack_server'
[2016-11-21 19:23:58,759] [DEBUG] [storage:569] (31942.140735943119808) Try 'http'
[2016-11-21 19:23:58,759] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'http'
[2016-11-21 19:23:58,759] [DEBUG] [storage:569] (31942.140735943119808) Try 'dht'
[2016-11-21 19:25:14,035] [ERROR] [storage:573] (31942.140735943119808) [Errno 60] Operation timed out
Traceback (most recent call last):
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/storage.py", line 570, in put_immutable_data
    rc = handler.put_immutable_handler( data_hash, data_text, txid )
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dht.py", line 198, in put_immutable_handler
    return dht_put_data(key, data)
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dht.py", line 131, in dht_put_data
    return dht_client.set(data_key, data_value)
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 46, in default
    return self.request()
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 62, in request
    self.ensure_connected()
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 55, in ensure_connected
    self.sock.connect((self.server, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 60] Operation timed out
[2016-11-21 19:25:14,040] [DEBUG] [storage:553] (31942.140735943119808) put_immutable_data(60ef539a835ec02c5ad87892345e4f559cf97420), required=
[2016-11-21 19:25:14,040] [DEBUG] [storage:569] (31942.140735943119808) Try 'disk'
[2016-11-21 19:25:14,040] [DEBUG] [disk:181] (31942) Stored to '/Users/larry/.blockstack/storage-disk/immutable/60ef539a835ec02c5ad87892345e4f559cf97420'
[2016-11-21 19:25:14,041] [DEBUG] [storage:585] (31942.140735943119808) Replication succeeded with 'disk'
[2016-11-21 19:25:14,041] [DEBUG] [storage:569] (31942.140735943119808) Try 'blockstack_resolver'
[2016-11-21 19:25:14,041] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'blockstack_resolver'
[2016-11-21 19:25:14,041] [DEBUG] [storage:569] (31942.140735943119808) Try 'blockstack_server'
[2016-11-21 19:25:14,050] [DEBUG] [blockstack_server:152] (31942) Replicate zonefile for 60ef539a835ec02c5ad87892345e4f559cf97420
[2016-11-21 19:25:14,738] [ERROR] [blockstack_server:164] (31942) Server node.blockstack.org:6264 failed to save 60ef539a835ec02c5ad87892345e4f559cf97420
[2016-11-21 19:25:14,738] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'blockstack_server'
[2016-11-21 19:25:14,738] [DEBUG] [storage:569] (31942.140735943119808) Try 'http'
[2016-11-21 19:25:14,738] [DEBUG] [storage:582] (31942.140735943119808) Failed to replicate with 'http'
[2016-11-21 19:25:14,738] [DEBUG] [storage:569] (31942.140735943119808) Try 'dht'
[2016-11-21 19:26:30,148] [ERROR] [storage:573] (31942.140735943119808) [Errno 60] Operation timed out
Traceback (most recent call last):
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/storage.py", line 570, in put_immutable_data
    rc = handler.put_immutable_handler( data_hash, data_text, txid )
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dht.py", line 198, in put_immutable_handler
    return dht_put_data(key, data)
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dht.py", line 131, in dht_put_data
    return dht_client.set(data_key, data_value)
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 46, in default
    return self.request()
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 62, in request
    self.ensure_connected()
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/basicrpc/basicrpc.py", line 55, in ensure_connected
    self.sock.connect((self.server, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 60] Operation timed out
{
    "immutable_data_hash": "9724c1e20e6e3e4d7f57ed25f9d4efb006e508590d528c90da597f6a775c13e5", 
    "status": true, 
    "transaction_hash": "40e728b600a0b424b4cadf53222007a69b924f831c0be744bb8d5825faba53a8", 
    "zonefile": {
        "$origin": "devname0.id", 
        "$ttl": 3600, 
        "txt": [
            {
                "name": "test", 
                "txt": "#9724c1e20e6e3e4d7f57ed25f9d4efb006e508590d528c90da597f6a775c13e5"
            }
        ], 
        "uri": [
            {
                "_missing_class": true, 
                "class": "IN", 
                "name": "_http._tcp", 
                "priority": 10, 
                "target": "https://www.larrysalibra.com/blockstack-data/devname0.id/profile.json", 
                "weight": 1
            }
        ]
    }, 
    "zonefile_hash": "60ef539a835ec02c5ad87892345e4f559cf97420"
}
```

Now the name (`devname0.id`) is in a state that causes errors when I try to use commands such as `blockstack lookup` or `blockstack get_name_zonefile` because presumably it can't find the zonefile. If that's the case, we might want to make the error clearer along with suggestions as to a course of action for the user to take to fix the problem: 

```
(blockstack-venv) larry@blockstack-explorer-1:~$ blockstack lookup devname0.id
[2016-11-21 10:20:23,802] [DEBUG] [spv:103] (4235.140559050532672) Using mainnet
[2016-11-21 10:20:24,059] [DEBUG] [cli:210] (4235.140559050532672) Enabling advanced methods
[2016-11-21 10:20:24,085] [DEBUG] [client:100] (4235.140559050532672) Connect to localhost:6264
[2016-11-21 10:20:24,115] [DEBUG] [client:135] (4235.140559050532672) Loaded storage driver 'disk'
[2016-11-21 10:20:24,115] [DEBUG] [client:135] (4235.140559050532672) Loaded storage driver 'blockstack_resolver'
[2016-11-21 10:20:24,115] [DEBUG] [client:135] (4235.140559050532672) Loaded storage driver 'blockstack_server'
[2016-11-21 10:20:24,116] [DEBUG] [client:135] (4235.140559050532672) Loaded storage driver 'http'
[2016-11-21 10:20:24,116] [DEBUG] [client:135] (4235.140559050532672) Loaded storage driver 'dht'
[2016-11-21 10:20:24,213] [DEBUG] [profile:154] (4235.140559050532672) Fetched 60ef539a835ec02c5ad87892345e4f559cf97420 from Atlas peer localhost:6264
[2016-11-21 10:20:24,214] [ERROR] [actions:741] (4235.140559050532672) u'60ef539a835ec02c5ad87892345e4f559cf97420'
Traceback (most recent call last):
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 734, in cli_lookup
    user_profile, user_zonefile = get_name_profile(str(args.name), name_record=blockchain_record, include_raw_zonefile=True)
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 430, in get_name_profile
    user_zonefile = get_name_zonefile( name, create_if_absent=create_if_absent, proxy=proxy, name_record=name_record, include_name_record=True, storage_drivers=zonefile_storage_drivers, include_raw_zonefile=include_raw_zonefile )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 369, in get_name_zonefile
    raw_zonefile_data = load_name_zonefile(name, user_zonefile_hash, storage_drivers=storage_drivers, raw_zonefile=True, proxy=proxy )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 155, in load_name_zonefile
    zonefile_txt = res['zonefiles'][expected_zonefile_hash]
KeyError: u'60ef539a835ec02c5ad87892345e4f559cf97420'
Failed to look up name
Traceback (most recent call last):
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/actions.py", line 734, in cli_lookup
    user_profile, user_zonefile = get_name_profile(str(args.name), name_record=blockchain_record, include_raw_zonefile=True)
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 430, in get_name_profile
    user_zonefile = get_name_zonefile( name, create_if_absent=create_if_absent, proxy=proxy, name_record=name_record, include_name_record=True, storage_drivers=zonefile_storage_drivers, include_raw_zonefile=include_raw_zonefile )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 369, in get_name_zonefile
    raw_zonefile_data = load_name_zonefile(name, user_zonefile_hash, storage_drivers=storage_drivers, raw_zonefile=True, proxy=proxy )
  File "/home/dev/blockstack-venv/local/lib/python2.7/site-packages/blockstack_client/profile.py", line 155, in load_name_zonefile
    zonefile_txt = res['zonefiles'][expected_zonefile_hash]
KeyError: u'60ef539a835ec02c5ad87892345e4f559cf97420'

(blockstack-venv) larry@blockstack-explorer-1:~$
```

**Comment by jcnelson** [comment]
Hi Larry, thank you as always for your detailed traces :)  I think this is fixed with the latest push to master and PyPI.  Please let me know if the problem continues.

**Comment by larrysalibra** [comment]
Looks like this works. Thank you!
