### ISSUE TITLE
put_mutable fails with NameError

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#174]
Error is `NameError: global name 'privkey' is not defined`

Version:

```JSON
{
    "advanced_mode": true, 
    "cli_version": "0.14.0.7", 
    "consensus_hash": "324abae20d8dfa59c78d18b865e3a9d7", 
    "last_block_processed": 440943, 
    "last_block_seen": 440950, 
    "server_alive": true, 
    "server_host": "node.blockstack.org", 
    "server_port": 6264, 
    "server_version": "0.14.1"
}
```
Full trace:

```
(blockstack-venv)Tesla:venv larry$ blockstack put_mutable
[2016-11-28 16:59:41,961] [DEBUG] [spv:103] (20552.140736149173184) Using mainnet
[2016-11-28 16:59:42,247] [DEBUG] [cli:210] (20552.140736149173184) Enabling advanced methods
usage: blockstack put_mutable [-h] name data_id data
blockstack put_mutable: error: too few arguments
[2016-11-28 16:59:42,282] [DEBUG] [client:100] (20552.140736149173184) Connect to node.blockstack.org:6264
[2016-11-28 16:59:42,312] [DEBUG] [client:135] (20552.140736149173184) Loaded storage driver 'disk'
[2016-11-28 16:59:42,312] [DEBUG] [client:135] (20552.140736149173184) Loaded storage driver 'blockstack_resolver'
[2016-11-28 16:59:42,313] [DEBUG] [client:135] (20552.140736149173184) Loaded storage driver 'blockstack_server'
[2016-11-28 16:59:42,313] [DEBUG] [client:135] (20552.140736149173184) Loaded storage driver 'http'
[2016-11-28 16:59:42,313] [DEBUG] [client:135] (20552.140736149173184) Loaded storage driver 'dht'

Interactive prompt engaged.  Press Ctrl+C to quit
Help for 'put_mutable': Put mutable data into a profile

The name to receive the data ('name'): devname0.id
The name of the data ('data_id'): fruit
The JSON-formatted data to store ('data'): {}
[2016-11-28 16:59:51,971] [DEBUG] [rpc:793] (20552.140736149173184) RPC running (/Users/larry/.blockstack/api_endpoint.pid)
[2016-11-28 16:59:51,972] [DEBUG] [rpc:843] (20552.140736149173184) RPC endpoint already running (/Users/larry/.blockstack)
[2016-11-28 16:59:51,984] [DEBUG] [rpc:452] (20552.140736149173184) Connect to RPC at localhost:6270
[2016-11-28 16:59:53,482] [DEBUG] [rpc:452] (20552.140736149173184) Connect to RPC at localhost:6270
[2016-11-28 16:59:56,292] [DEBUG] [profile:155] (20552.140736149173184) Fetched 60ef539a835ec02c5ad87892345e4f559cf97420 from Atlas peer node.blockstack.org:6264
[2016-11-28 16:59:56,302] [WARNING] [profile:236] (20552.140736149173184) No data public key set; falling back to hash of data and/or owner public key for profile authentication
[2016-11-28 16:59:56,302] [DEBUG] [storage:507] (20552.140736149173184) get_mutable devname0.id
[2016-11-28 16:59:56,302] [DEBUG] [storage:547] (20552.140736149173184) Try http (https://www.larrysalibra.com/blockstack-data/devname0.id/profile.json)
[2016-11-28 17:00:02,029] [DEBUG] [storage:238] (20552.140736149173184) Verified with 1A9gp5evvELwaizkA44wUuzAcQiPHkKWWP
[2016-11-28 17:00:02,029] [DEBUG] [storage:577] (20552.140736149173184) loaded 'https://www.larrysalibra.com/blockstack-data/devname0.id/profile.json' with http
[2016-11-28 17:00:02,029] [DEBUG] [user:774] (20552.140736149173184) No mutable data zonefiles installed for 'fruit'
[2016-11-28 17:00:02,029] [ERROR] [keys:342] (20552.140736149173184) No data public key defined
[2016-11-28 17:00:02,029] [WARNING] [keys:385] (20552.140736149173184) No data private key set.  Falling back to owner keypair.
[2016-11-28 17:00:02,389] [DEBUG] [user:64] (20552.140736149173184) WARN: Scheme 'file' has no known transport protocol
[2016-11-28 17:00:02,878] [DEBUG] [storage:699] (20552.140736149173184) put_mutable_data(devname0.id), required=
[2016-11-28 17:00:02,878] [DEBUG] [storage:717] (20552.140736149173184) Try 'disk'
[2016-11-28 17:00:02,878] [DEBUG] [disk:217] (20552) Stored to '/Users/larry/.blockstack/storage-disk/mutable/devname0.id'
[2016-11-28 17:00:02,878] [DEBUG] [storage:717] (20552.140736149173184) Try 'blockstack_resolver'
[2016-11-28 17:00:02,878] [DEBUG] [storage:732] (20552.140736149173184) Failed to replicate with 'blockstack_resolver'
[2016-11-28 17:00:02,878] [DEBUG] [storage:717] (20552.140736149173184) Try 'blockstack_server'
[2016-11-28 17:00:02,879] [DEBUG] [blockstack_server:171] (20552) Replicate profile for devname0.id
[2016-11-28 17:00:02,879] [DEBUG] [blockstack_server:106] (20552) Get profile for devname0.id
[2016-11-28 17:00:03,631] [DEBUG] [rpc:452] (20552.140736149173184) Connect to RPC at localhost:6270
[2016-11-28 17:00:05,257] [ERROR] [storage:720] (20552.140736149173184) global name 'privkey' is not defined
Traceback (most recent call last):
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/storage.py", line 718, in put_mutable_data
    rc = handler.put_mutable_handler( fq_data_id, serialized_data, fqu=fqu )
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/blockstack_server.py", line 277, in put_mutable_handler
    return put_data( data_id, data_bin, zonefile=False, fqu=kw.get('fqu', None) )
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/blockstack_server.py", line 187, in put_data
    sigb64 = blockstack_client.storage.sign_raw_data( "%s%s" % (cur_profile_hash, data_txt), data_privkey )
  File "/Users/larry/venv/blockstack-venv/lib/python2.7/site-packages/blockstack_client/storage.py", line 385, in sign_raw_data
    pk = ECPrivateKey(privkey[:64])
NameError: global name 'privkey' is not defined
[2016-11-28 17:00:05,260] [DEBUG] [storage:717] (20552.140736149173184) Try 'http'
[2016-11-28 17:00:05,260] [DEBUG] [storage:732] (20552.140736149173184) Failed to replicate with 'http'
[2016-11-28 17:00:05,260] [DEBUG] [storage:717] (20552.140736149173184) Try 'dht'
[2016-11-28 17:00:06,388] [DEBUG] [storage:699] (20552.140736149173184) put_mutable_data(devname0.id:fruit), required=
[2016-11-28 17:00:06,389] [DEBUG] [storage:717] (20552.140736149173184) Try 'disk'
[2016-11-28 17:00:06,391] [DEBUG] [disk:217] (20552) Stored to '/Users/larry/.blockstack/storage-disk/mutable/devname0.id:fruit'
[2016-11-28 17:00:06,391] [DEBUG] [storage:717] (20552.140736149173184) Try 'blockstack_resolver'
[2016-11-28 17:00:06,391] [DEBUG] [storage:732] (20552.140736149173184) Failed to replicate with 'blockstack_resolver'
[2016-11-28 17:00:06,391] [DEBUG] [storage:717] (20552.140736149173184) Try 'blockstack_server'
[2016-11-28 17:00:06,392] [DEBUG] [storage:732] (20552.140736149173184) Failed to replicate with 'blockstack_server'
[2016-11-28 17:00:06,392] [DEBUG] [storage:717] (20552.140736149173184) Try 'http'
[2016-11-28 17:00:06,392] [DEBUG] [storage:732] (20552.140736149173184) Failed to replicate with 'http'
[2016-11-28 17:00:06,392] [DEBUG] [storage:717] (20552.140736149173184) Try 'dht'
[2016-11-28 17:00:06,831] [WARNING] [data:144] (20552.140736149173184) No metadata directory found; cannot store version of 'devname0.id:fruit'
Failed to store mutable data version
(blockstack-venv)Tesla:venv larry$
```

**Comment by jcnelson** [comment]
Hi Larry, thanks for reporting!  I'm looking into this now.  We're revamping the storage API for 0.14.1, which will also bring browser application support.

**Comment by jcnelson** [comment]
This interface shouldn't be public; we'll be using the datastore API instead.
