### ISSUE TITLE
KeyError: 'blockstack-client'

### ISSUE THREAD

**Issue by dmonay** [stx-labs/stacks.js#194]
I had installed `blockstack cli` a month ago, set up a wallet, and registered a name. Today I went back to the cli and I get the following error whenever I execute the `blockstack` command with any arguments, be it `blockstack lookup timblee.id` or `blockstack --help`:
```
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 91, in <module>
    res = configure(interactive=False, force=False)
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/config.py", line 643, in configure
    blockstack_opts_defaults = read_config_file( path=config_file )['blockstack-client']
KeyError: 'blockstack-client'
```

I had followed the instructions [here](https://blockstack.org/docs) and installed the client using pip. Today I ran `sudo pip install blockstack --upgrade` and have `blockstack-0.14.0.12` installed now.

I'm on macOS 10.12.3 (16D32).

Any clarity on this issue and how to fix it is appreciated.

**Comment by dmonay** [comment]
Seems that it was an issue with my setup. I think Little Flocker was actually messing with this. Closing issue.
