### ISSUE TITLE
Malformed JSON Web Token in AuthRequest 

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#217]

**Comment by kantai** [comment]
When I go to https://helloblockstack.com/

The auth redirect sends me to:

http://localhost:3000/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJqdGkiOiJmMWQzZjVlNC04NzA3LTRjODktODFiMC1kNjgwZjQ2M2NkMWYiLCJpYXQiOjE0OTgwNTM3NDUsImV4cCI6MTQ5ODA1NzM0NSwiaXNzIjpudWxsLCJwdWJsaWNfa2V5cyI6W10sImRvbWFpbl9uYW1lIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1hbmlmZXN0X3VyaSI6Imh0dHBzOi8vaGVsbG9ibG9ja3N0YWNrLmNvbS9tYW5pZmVzdC5qc29uIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9oZWxsb2Jsb2Nrc3RhY2suY29tLyIsInNjb3BlcyI6W119.

The token string

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJqdGkiOiJmMWQzZjVlNC04NzA3LTRjODktODFiMC1kNjgwZjQ2M2NkMWYiLCJpYXQiOjE0OTgwNTM3NDUsImV4cCI6MTQ5ODA1NzM0NSwiaXNzIjpudWxsLCJwdWJsaWNfa2V5cyI6W10sImRvbWFpbl9uYW1lIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1hbmlmZXN0X3VyaSI6Imh0dHBzOi8vaGVsbG9ibG9ja3N0YWNrLmNvbS9tYW5pZmVzdC5qc29uIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9oZWxsb2Jsb2Nrc3RhY2suY29tLyIsInNjb3BlcyI6W119.
```

is malformed, gives me a "Token should have three parts" error in Blockstack Browser.

**Comment by larrysalibra** [comment]
Thanks for reporting this @kantai !
> is malformed, gives me a "Token should have three parts" error in Blockstack Browser.

That token string isn't malformed - it has 3 parts. It's just unsigned because helloblockstack.com and everything else deployed (forum, etc) don't provide app private keys to `makeAuthRequest`: https://github.com/blockstack/blockstack-app-generator/blob/master/app/templates/public/app.js#L5

When no private key is provided, an unsecured token is created: https://github.com/blockstack/blockstack.js/blob/develop-larry/src/auth/authMessages.js#L43 

However, the reason you saw this error in browser regarding the malformed token was because I transposed 2 arguments...it was trying to decode a username as a token. That's now fixed in `v0.10` of browser: https://github.com/blockstack/blockstack-browser/commit/619a51bd7dd9eb69ba851b7b55c16f21155f8dd6

This leads us to another problem, core changed the validation schema for requests for core session tokens to require tokens signed by app's private keys:

https://github.com/blockstack/blockstack-core/commit/2e2931f2955bc3b1106aa46798bdcfa0748df195#diff-ec0ac14571d4c36771b3b01b454f24a8L428

This results in the following error:

```
[2017-06-22 02:19:12,966] [ERROR] [rpc:439] (1103.140735941780416) 'app_public_keys' is a required property

Failed validating 'required' in schema:
    {'properties': {'app_domain': {'anyOf': [{'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$',
                                              'type': 'string'},
                                             {'pattern': '^([a-z0-9+]+)://([a-zA-Z0-9\\-_.~%#?&\\\\:/=]+)$',
                                              'type': 'string'}]},
                    'app_private_key': {'pattern': '^([0-9a-fA-F]+)$',
                                        'type': 'string'},
                    'app_public_keys': {'items': {'properties': {'device_id': {'pattern': '.+',
                                                                               'type': 'string'},
                                                                 'public_key': {'pattern': '^([0-9a-fA-F]+)$',
                                                                                'type': 'string'}},
                                                  'required': ['public_key',
                                                               'device_id'],
                                                  'type': 'object'},
                                        'type': 'array'},
                    'blockchain_id': {'pattern': '^([a-z0-9\\-_.+]{3,37})$',
                                      'type': 'string'},
                    'device_id': {'pattern': '.+', 'type': 'string'},
                    'methods': {'items': {'pattern': '^[a-zA-Z_][a-zA-Z0-9_.]+$',
                                          'type': 'string'},
                                'type': 'array'},
                    'version': {'maximum': 1,
                                'minimum': 1,
                                'type': 'integer'}},
     'required': ['app_public_keys',
                  'app_domain',
                  'version',
                  'methods',
                  'blockchain_id',
                  'app_private_key',
                  'device_id'],
     'type': 'object'}

On instance:
    {u'app_domain': u'helloblockstack.com',
     u'app_public_key': u'02ac600317bdb22ceadf151b64496479b82a8d92e3d079e7c8b5b036d04ce5a2b7',
     u'methods': []}
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 436, in GET_auth
    jsonschema.validate(decoded_token['payload'], APP_SESSION_REQUEST_SCHEMA )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: 'app_public_keys' is a required property

Failed validating 'required' in schema:
    {'properties': {'app_domain': {'anyOf': [{'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$',
                                              'type': 'string'},
                                             {'pattern': '^([a-z0-9+]+)://([a-zA-Z0-9\\-_.~%#?&\\\\:/=]+)$',
                                              'type': 'string'}]},
                    'app_private_key': {'pattern': '^([0-9a-fA-F]+)$',
                                        'type': 'string'},
                    'app_public_keys': {'items': {'properties': {'device_id': {'pattern': '.+',
                                                                               'type': 'string'},
                                                                 'public_key': {'pattern': '^([0-9a-fA-F]+)$',
                                                                                'type': 'string'}},
                                                  'required': ['public_key',
                                                               'device_id'],
                                                  'type': 'object'},
                                        'type': 'array'},
                    'blockchain_id': {'pattern': '^([a-z0-9\\-_.+]{3,37})$',
                                      'type': 'string'},
                    'device_id': {'pattern': '.+', 'type': 'string'},
                    'methods': {'items': {'pattern': '^[a-zA-Z_][a-zA-Z0-9_.]+$',
                                          'type': 'string'},
                                'type': 'array'},
                    'version': {'maximum': 1,
                                'minimum': 1,
                                'type': 'integer'}},
     'required': ['app_public_keys',
                  'app_domain',
                  'version',
                  'methods',
                  'blockchain_id',
                  'app_private_key',
                  'device_id'],
     'type': 'object'}

On instance:
    {u'app_domain': u'helloblockstack.com',
     u'app_public_key': u'02ac600317bdb22ceadf151b64496479b82a8d92e3d079e7c8b5b036d04ce5a2b7',
     u'methods': []}
[2017-06-22 02:19:12,979] [DEBUG] [rpc:443] (1103.140735941780416) Invalid token
127.0.0.1 - - [22/Jun/2017 02:19:12] "GET /v1/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJhcHBfZG9tYWluIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1ldGhvZHMiOltdLCJhcHBfcHVibGljX2tleSI6IjAyYWM2MDAzMTdiZGIyMmNlYWRmMTUxYjY0NDk2NDc5YjgyYThkOTJlM2QwNzllN2M4YjViMDM2ZDA0Y2U1YTJiNyJ9.DtWKBvHdz0i40J20l7tiUo-cFVqripvjhNDYMw0S5bN1XIEq2Nb2HbcSX2el37vKel30vc6-yYRnuPf0CwGZGw HTTP/1.1" 401 -

```

**Comment by kantai** [comment]
And this is the failing Core test:

https://github.com/blockstack/blockstack-core/blob/rc-0.14.2/integration_tests/blockstack_integration_tests/live_tests/api_tests.py#L137

Sorry, I should have raised an alarm about this test earlier, but I assumed that a change to the token specification was agreed on and that the _test_ was wrong --- faulty assumption.

**Comment by larrysalibra** [comment]
This bug appears to have been resolved.
