### ISSUE TITLE
get_consensus_at broken: no logger in utils.py

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#26]
`get_consensus_at` doesn't work in version 0.0.7 because there's no `log` defined in `util.py`.

```
root@blockchainid:~# blockstore-cli get_consensus_at 385159
Traceback (most recent call last):
  File "/usr/local/bin/blockstore-cli", line 928, in <module>
    run_cli()
  File "/usr/local/bin/blockstore-cli", line 925, in run_cli
    print_result(result)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/utils.py", line 46, in print_result
    print pretty_dump(json_str)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/utils.py", line 40, in pretty_dump
    log.debug("ERROR in pretty print: %s" % e)
NameError: global name 'log' is not defined
root@blockchainid:~#
```

**Comment by larrysalibra** [comment]
I added `from config import log` which solves the `NameError` but now getting other strange errors:

```
root@blockchainid:~# blockstore-cli get_consensus_at 385159
[DEBUG] [utils:40] (14105) ERROR in pretty print: expected string or buffer
null
root@blockchainid:~# nano +876 /usr/local/lib/python2.7/dist-packages/blockstore_client/utils.py
root@blockchainid:~# blockstore-cli get_consensus_at 385100
[DEBUG] [utils:40] (14111) ERROR in pretty print: No JSON object could be decoded
"f"
root@blockchainid:~# blockstore-cli get_consensus_at 385000
1
root@blockchainid:~# blockstore-cli get_consensus_at 384000
0
root@blockchainid:~#
```

**Comment by larrysalibra** [comment]
`get_nameops_at` also seems affected by this (or something similar)

```
root@blockchainid:~# blockstore-cli get_nameops_at 385000
[DEBUG] [utils:40] (14166) ERROR in pretty print: expected string or buffer
[]
root@blockchainid:~# 
```

**Comment by muneeb-ali** [comment]
Here is the output of the two commands now:

```
(blockstore-client)muneeb@amsterdam:bin$ ./blockstore-cli get_consensus_at 384000
{
    "result": "00bc6f1800ea01674bcad0fdad8a1839"
}
```

and

```
(blockstore-client)muneeb@amsterdam:bin$ ./blockstore-cli get_nameops_at 385000
{}
```

As, @jcnelson mentioned that we're going to take another pass over the JSON RPC interface. And will be improving return formats etc of individual RPC calls.
