### ISSUE TITLE
pip install blockstack fails osx 10.11.4

### ISSUE THREAD

**Issue by iamsamwood** [stx-labs/stacks.js#69]
$ sudo pip install blockstack

fails with:

scrypt-1.1.6/lib/crypto/crypto_aesctr.c:38:10: fatal error: 'openssl/aes.h' file not found

I used the following to work around this:

$ env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install blockstack

but then hit:

copying LICENSE -> /System/Library/Frameworks/Python.framework/Versions/2.7/

error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/LICENSE'

(All of this was executed as root). 

sh-3.2# pip --version
pip 1.5.4 from /Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg (python 2.7)
sh-3.2# python --version
Python 2.7.10

**Comment by iamsamwood** [comment]
updating python and pip got past these errors:

brew install python
pip install --upgrade pip

but now I see:

ImportError: No module named utilitybelt

**Comment by muneeb-ali** [comment]
Can you post more details about the 'utilitybelt' error? Thanks!

**Comment by iamsamwood** [comment]
$ blockstack 
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstore_client.blockstore_cli import run_cli, exit_with_error
  File "/Library/Python/2.7/site-packages/blockstore_client/**init**.py", line 24, in <module>
    import client
  File "/Library/Python/2.7/site-packages/blockstore_client/client.py", line 37, in <module>
    import parsing, schemas, storage, drivers, config, spv, utils
  File "/Library/Python/2.7/site-packages/blockstore_client/schemas.py", line 26, in <module>
    from pybitcoin.formatcheck import is_b58check_address
  File "/Library/Python/2.7/site-packages/pybitcoin/**init**.py", line 10, in <module>
    import services
  File "/Library/Python/2.7/site-packages/pybitcoin/services/**init**.py", line 12, in <module>
    from blockchain_info import BlockchainInfoClient
  File "/Library/Python/2.7/site-packages/pybitcoin/services/blockchain_info.py", line 11, in <module>
    from ..hash import reverse_hash
  File "/Library/Python/2.7/site-packages/pybitcoin/hash.py", line 13, in <module>
    from utilitybelt import is_hex
ImportError: No module named utility belt

$ python --version
Python 2.7.11
$ pip --version
pip 8.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ brew --version
Homebrew 0.9.5 (git revision 1a266; last commit 2015-12-13)

**Comment by koppenhoefer** [comment]
FYI, I'm seeing a similar problem,.. with slightly different version numbers... under OS X 10.11.5
So although the "sudo pip install blockstack" succeeds,
running blockstack on my OS X failed :(... but then succeeded (jump to EOF). :)

...Installing collected packages: blockstack
  Running setup.py install for blockstack ... done
**Successfully installed blockstack-0.0.10.7**
stidhcp-3-115:~ koppenho$ **blockstack**
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstore_client.blockstore_cli import run_cli, exit_with_error
  File "/Library/Python/2.7/site-packages/blockstore_client/**init**.py", line 24, in <module>
    import client
  File "/Library/Python/2.7/site-packages/blockstore_client/client.py", line 37, in <module>
    import parsing, schemas, storage, drivers, config, spv, utils
  File "/Library/Python/2.7/site-packages/blockstore_client/storage.py", line 43, in <module>
    from config import log
  File "/Library/Python/2.7/site-packages/blockstore_client/config.py", line 27, in <module>
    import virtualchain
  File "/Library/Python/2.7/site-packages/virtualchain/**init**.py", line 28, in <module>
    from virtualchain import setup_virtualchain, run_virtualchain, stop_virtualchain, sync_virtualchain, stop_sync_virtualchain, virtualchain_set_opfields
  File "/Library/Python/2.7/site-packages/virtualchain/virtualchain.py", line 38, in <module>
    from txjsonrpc.netstring import jsonrpc
  File "/Library/Python/2.7/site-packages/txjsonrpc/netstring/jsonrpc.py", line 11, in <module>
    from twisted.internet import defer, protocol, reactor
  File "/Library/Python/2.7/site-packages/twisted/**init**.py", line 55, in <module>
    _checkRequirements()
  File "/Library/Python/2.7/site-packages/twisted/__init__.py", line 42, in _checkRequirements
    raise ImportError(required + ".")

### ImportError: Twisted requires zope.interface 3.6.0 or later.

stidhcp-3-115:~ koppenho$ python --version
Python 2.7.10
stidhcp-3-115:~ koppenho$ pip --version
pip 8.1.2 from /Library/Python/2.7/site-packages (python 2.7)
stidhcp-3-115:~ koppenho$ brew --version
Homebrew 0.9.9 (git revision aae44; last commit 2016-05-13)
Homebrew/homebrew-core (git revision b4a5; last commit 2016-05-13)

Note that after doing the following,.. I got further:

### pip install zope.interface --upgrade

stidhcp-3-115:zope.interface-3.6.0 koppenho$ blockstack
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstore_client.blockstore_cli import run_cli, exit_with_error
  File "/Library/Python/2.7/site-packages/blockstore_client/**init**.py", line 24, in <module>
    import client
  File "/Library/Python/2.7/site-packages/blockstore_client/client.py", line 37, in <module>
    import parsing, schemas, storage, drivers, config, spv, utils
  File "/Library/Python/2.7/site-packages/blockstore_client/storage.py", line 43, in <module>
    from config import log
  File "/Library/Python/2.7/site-packages/blockstore_client/config.py", line 27, in <module>
    import virtualchain
  File "/Library/Python/2.7/site-packages/virtualchain/**init**.py", line 28, in <module>
    from virtualchain import setup_virtualchain, run_virtualchain, stop_virtualchain, sync_virtualchain, stop_sync_virtualchain, virtualchain_set_opfields
  File "/Library/Python/2.7/site-packages/virtualchain/virtualchain.py", line 38, in <module>
    from txjsonrpc.netstring import jsonrpc
  File "/Library/Python/2.7/site-packages/txjsonrpc/netstring/jsonrpc.py", line 15, in <module>
    from txjsonrpc import jsonrpclib
  File "/Library/Python/2.7/site-packages/txjsonrpc/jsonrpclib.py", line 8, in <module>
    from six.moves import xmlrpc_client

### ImportError: cannot import name xmlrpc_client

What ultimately worked for me was to do this:

sudo rm -rf /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six*
sudo pip install six
Successfully installed six-1.10.0
stidhcp-3-115:python koppenho$ blockstack
usage: blockstack [-h]
              {balance,config,price,deposit,import,info,status,ping,lookup,names,register,transfer,update,whois}
Blockstack cli version 0.0.12.7

**yeah. success**
kudos to Cheng from here: http://bit.ly/ChengBo_isAgod

**Comment by jcnelson** [comment]
A lot of these problems should be fixed in the new stable release (i.e. we don't rely on Twisted any longer).  A new version of blockstack has been pushed to pip.  Please re-open if you're still seeing problems.

**Comment by koppenhoefer** [comment]
Just for fun, I've returned on a fresh system a year later,.. I am now on a freshly installed (not upgrade) 10.12.4. I just installed Brew. Then did the OS X installations, with no errors, from https://blockstack.org/docs.

BUT,.. running 'Blockstack',.. I get this:

```
$ blockstack
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/app.py", line 40, in <module>
    import wallet
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/wallet.py", line 50, in <module>
    from .backend.crypto.utils import get_address_from_privkey
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/__init__.py", line 21, in <module>
    import registrar
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/registrar.py", line 49, in <module>
    from .queue import get_queue_state, in_queue, queue_removeall
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/backend/queue.py", line 33, in <module>
    from ..proxy import get_default_proxy
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/proxy.py", line 42, in <module>
    import storage
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/storage.py", line 47, in <module>
    from scripts import is_name_valid
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/scripts.py", line 38, in <module>
    from .keys import *
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/keys.py", line 42, in <module>
    import fastecdsa.curve
  File "/usr/local/lib/python2.7/site-packages/fastecdsa/curve.py", line 1, in <module>
    from fastecdsa import curvemath
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/fastecdsa/curvemath.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/fastecdsa/curvemath.so
  Reason: image not found
```

So no... the new release doesn't appear to be an improved experience.
Just sayin.

**Comment by muneeb-ali** [comment]
@koppenhoefer thanks for sending the feedback! We're in the process of updating docs on our website (I just created [this issue](https://github.com/blockstack/blockstack.org/issues/269)). The Blockstack Core [README](https://github.com/blockstack/blockstack-core/blob/master/README.md) has the most recent installation guide. 

From the log, I see that you're having issues with the fastecdsa installation. From the README, here are the instructions for macOS:

For macOS:

```
$ brew install gmp libffi openssl
$ sudo pip install --upgrade pip
$ sudo pip install blockstack --upgrade
```

Can you kindly try them out and see if this works? We're happy to help you with any issue. Apologies that you're having trouble. Blockstack Core packs a lot of complexity in it and getting it running smoothly on various distributions is a non-trivial issue. We're trying our best and have recently rolled out [Azure images](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/blockstack.blockstack-core-v14), [AWS images](https://aws.amazon.com/marketplace/pp/B06XGBTRD7), and [docker images](https://github.com/blockstack/blockstack-core/tree/api/images/docker) to try and make the process easier. Your feedback can help us improve more!

**Comment by koppenhoefer** [comment]
@muneeb-ali thanks for your swift and useful message.

YES, I confirm that your instructions fixed the issue for me. Thank-you!
