### ISSUE TITLE
pip install blockstack fails Ubuntu 14.04: ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.

### ISSUE THREAD

**Issue by lxw0109** [stx-labs/stacks.js#70]
I installed blockstack on  Ubuntu 14.04, and run the command 
`sudo blockstack lookup fredwilson.id`
But fail with:
`ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.`
Details as follows:
`lxw@ubuntu:~ » sudo blockstack lookup fredwilson.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 34, in <module>
    from blockstore_client.blockstore_cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/__init__.py", line 24, in <module>
    import client
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/client.py", line 37, in <module>
    import parsing, schemas, storage, drivers, config, spv, utils
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/storage.py", line 43, in <module>
    from config import log
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/config.py", line 27, in <module>
    import virtualchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/__init__.py", line 28, in <module>
    from virtualchain import setup_virtualchain, run_virtualchain, stop_virtualchain, sync_virtualchain, stop_sync_virtualchain, virtualchain_set_opfields
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 38, in <module>
    from txjsonrpc.netstring import jsonrpc
  File "/usr/local/lib/python2.7/dist-packages/txjsonrpc/netstring/jsonrpc.py", line 11, in <module>
    from twisted.internet import defer, protocol, reactor
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 53, in <module>
    _checkRequirements()
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 37, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
**ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.**
`

**Comment by jcnelson** [comment]
The `develop` branch no longer requires Twisted, or this particular dependency.

**Comment by john-light** [comment]
@jcnelson I am duplicating this issue, can you please either provide an estimate as to approximately when the next release will be out, or else provide instructions for how to build blockstack-cli from the `develop` branch? (the latter may resolve #71)

**Comment by jcnelson** [comment]
The new release should not longer have this problem, since it no longer relies on Twisted.
