### ISSUE TITLE
Rename parser.py

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#81]
I was trying to install blockstack-profiles package which pulls in pycparser and noticed the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/muneeb/Dropbox (Personal)/work/blockstack/registrar/registrar/debug.py", line 16, in <module>
    from blockstack_profiles import resolve_zone_file_to_profile
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/blockstack_profiles/__init__.py", line 1, in <module>
    from token_signing import sign_token_record, sign_token_records
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/blockstack_profiles/token_signing.py", line 5, in <module>
    from jsontokens import TokenSigner, TokenVerifier, decode_token
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/jsontokens/token_signer.py", line 15, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/pkg_resources/__init__.py", line 71, in <module>
    import parser
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/blockstore_client/parser.py", line 24, in <module>
    import config
  File "/Users/muneeb/.virtualenvs/registrar/lib/python2.7/site-packages/blockstore_client/config.py", line 31, in <module>
```

There seems to be a conflict between parser.py in our client package and pycparser and currently we cannot install both the client and blockstack-profiles in the same virtualenv.

**Comment by jcnelson** [comment]
Will rename `parser.py` in the `develop` branch.

**Comment by muneeb-ali** [comment]
I can confirm that renaming parser.py resolves this issue.

**Comment by jcnelson** [comment]
This is done in the `develop` branch.

**Comment by jcnelson** [comment]
Fixed in the new release.
