### ISSUE TITLE
"ValueError: No JSON object could be decoded" when looking up onename account

### ISSUE THREAD

**Issue by zan-kusterle** [stx-labs/stacks.js#87]
> blockstack lookup zankusterle1.id

Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/blockstore_client/user.py", line 75, in parse_user
   user = json.loads( user_json.strip() )
 File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 339, in loads
   return _default_decoder.decode(s)
 File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
   raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
{
   "data_record": null
}

**Comment by muneeb-ali** [comment]
This is because of the new profile storage system. A fix is in place in a [hotfix branch](https://github.com/blockstack/blockstack-cli/tree/hotfix-renaming). Basically, the old version of the CLI doesn't know how to display the profiles v3 properly. You will need to upgrade the CLI:

> pip install blockstack --upgrade

After we push this to PyPi. ETA is 24-48 hours. We'll also update this issue once the new version is pushed to live. Would love to get your feedback and confirm that it resolved the issue.

**Comment by zan-kusterle** [comment]
It's working for me now.

**Comment by muneeb-ali** [comment]
Please try the new version. 

Installation instructions are here: https://github.com/blockstack/blockstack-cli/blob/master/README.md

**Comment by jcnelson** [comment]
Cleaning up old issues.  Going to go ahead and close this one, since it was reported as fixed.  Please re-open if problem persists.
