### ISSUE TITLE
CLI Stacking bug, eligibility check works but actually stacking fails

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#886]
**Describe the bug**
The check to see if the transaction is eligible works without any problem, but the actual stacking action fails

**What version of Blockstack.js are you using?**
 @stacks/cli@1.0.0-beta.20

**To Reproduce**

```
TWs-MacBook-Pro:~ tw$ stx can_stack 90000000000000 1 1PRgm3vsJjHCt2qQmNoSA8uBvTVfBwnLKL STD3RQDRX9E5437Y59A0FK2RFJBQ0SCCM9PEE3S2 -t
{ eligible: true }

TWs-MacBook-Pro:~ tw$ stx stack 90000000000000 1 1PRgm3vsJjHCt2qQmNoSA8uBvTVfBwnLKL 82d3449c0e185a9027c766fccd073a6b20f276e83fcc241f721cf5e4b6ec68b901
TypeError: Cannot read property 'startsWith' of undefined
    at /Users/tw/.nvm/versions/node/v13.13.0/lib/node_modules/@stacks/cli/node_modules/@stacks/stacking/src/index.ts:158:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async Promise.all (index 3)
TWs-MacBook-Pro:~ tw$ 
```
<img width="826" alt="Screen Shot 2020-12-16 at 12 34 49 PM" src="https://user-images.githubusercontent.com/49165468/102386139-b475d000-3f9c-11eb-9d3a-c145fdda4ecf.png">

**Comment by timstackblock** [comment]
https://github.com/blockstack/stacks.js/pull/857
