### ISSUE TITLE
I received an error when checking my balance with CLI on mainnet

### ISSUE THREAD

**Issue by timstackblock** [stx-labs/stacks.js#924]
**Describe the bug**
I received an error when checking my balance with CLI on mainnet

**To Reproduce**
1. Go to CLI
2. Run the command below and you will receive the error message

**Expected behavior**
Balance should return without issue
**Screenshots**
```
TWs-MacBook-Pro:stacks.js tw$ stx balance SP2PMEKV245CH97J5955FEWSTHN0BQY0Z0952XYSE
FetchError: request to http://core.blockstack.org:20443/v2/accounts/SP2PMEKV245CH97J5955FEWSTHN0BQY0Z0952XYSE?proof=0 failed, reason: connect ETIMEDOUT 172.67.24.94:20443
    at ClientRequest.<anonymous> (/Users/tw/.nvm/versions/node/v13.13.0/lib/node_modules/@stacks/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
request to http://core.blockstack.org:20443/v2/accounts/SP2PMEKV245CH97J5955FEWSTHN0BQY0Z0952XYSE?proof=0 failed, reason: connect ETIMEDOUT 172.67.24.94:20443
TWs-MacBook-Pro:stacks.js tw$ 
```

**Comment by agraebe** [comment]
can you check if you have the latest CLI version? this seems to use the old URL (`core.`)

**Comment by timstackblock** [comment]
It works not sure why I got this error
