### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by sjatkins** [stx-labs/stacks.js#96]
On ubuntu 16.0.4  from "sudo pip install blockstack" I am getting
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'

Anyone seen this or know what the problem may be?  I have updated setup-tools.

**Comment by sjatkins** [comment]
Oddly, it worked fine inside a virtualenv.   So I will proceed with that although I am curious what went wrong with a sudo top level install.

**Comment by jcnelson** [comment]
Hi @sjatkins, we just pushed a new stable release to PyPI that fixes a lot of the previously-reported packaging issues.  I'm going to go ahead and close this issue; please re-open if you're still seeing problems.  Thanks!
